spring:
  datasource:
    url: ${HW_DB_URL}
    username: ${HW_DB_USER}
    password: ${HW_DB_PASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    locations: classpath:db/migration
  web:
    resources:
      static-locations:
        - classpath:/META-INF/resources/
        - classpath:/resources/
        - classpath:/static/
        - classpath:/public/
        - file:/app/ui/

management:
  endpoints:
    web:
      exposure:
        include: health,info

hivewatch:
  auth:
    mode: ${HW_AUTH_MODE:DEV_HEADER}
    jwt:
      username-claim: ${HW_AUTH_JWT_USERNAME_CLAIM:preferred_username}
